<h1>Artificial Neural Network</h1>

In [ ]:
# Artificial Neural Network

# Installing Theano
# pip install --upgrade --no-deps git+git://github.com/Theano/Theano.git

# Installing Tensorflow
# Install Tensorflow from the website: https://www.tensorflow.org/versions/r0.12/get_started/os_setup.html

# Installing Keras
# pip install --upgrade keras

# Part 1 - Data Preprocessing

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv(r'C:\Users\...\Churn_Modelling.csv')
X = dataset.iloc[:, 3:13]
y = dataset.iloc[:, 13].values


In [2]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [3]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

# dummy for Gender
labelencoder_X = LabelEncoder()
X.iloc[:,2] = labelencoder_X.fit_transform(X.iloc[:,2])

#dummy for Country
dummy_GEO = pd.get_dummies(X["Geography"])
X.drop("Geography", axis = 1, inplace=True)
dummy_GEO.drop(columns=['Spain'], inplace=True)
X = pd.concat([X, dummy_GEO], axis=1)
X[0:5]

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  France  Germany  
0               1        101348.88       1        0  
1               1        112542.58       0        0  
2               0        113931.57       1        0  
3               0         93826.63       1        0  
4               1         79084.10       0        0

In [4]:
X=X.values
X[0:5]

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, 2.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0134888e+05, 1.0000000e+00, 0.0000000e+00],
       [6.0800000e+02, 0.0000000e+00, 4.1000000e+01, 1.0000000e+00,
        8.3807860e+04, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.1254258e+05, 0.0000000e+00, 0.0000000e+00],
       [5.0200000e+02, 0.0000000e+00, 4.2000000e+01, 8.0000000e+00,
        1.5966080e+05, 3.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.1393157e+05, 1.0000000e+00, 0.0000000e+00],
       [6.9900000e+02, 0.0000000e+00, 3.9000000e+01, 1.0000000e+00,
        0.0000000e+00, 2.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        9.3826630e+04, 1.0000000e+00, 0.0000000e+00],
       [8.5000000e+02, 0.0000000e+00, 4.3000000e+01, 2.0000000e+00,
        1.2551082e+05, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        7.9084100e+04, 0.0000000e+00, 0.0000000e+00]])

In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
import tensorflow as tf

In [9]:
from tensorflow import keras

In [10]:
from tensorflow.keras import layers

In [12]:
# Importing the Keras libraries and packages

#Firstly, you should download and set up the anaconda via anaconda and then open anaconda prompt and then
#follow these steps via TensorFlow. Fourthly, you should use 'pip install --ignore-installed --upgrade tensorflow==1.14.0'
#to install TensorFlow 1.14 on Conda Finally, you can use TensorFlow that is version 1.14 on python 3.7
# OR visit this website:https://www.tensorflow.org/install/pip
#from keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
# Initialising the ANN
classifier = tf.keras.Sequential()

In [14]:
# Adding the input layer and the first hidden layer

classifier.add(layers.Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [15]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [16]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [17]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [76]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

Train on 8000 samples
Epoch 1/100
8000/8000 [==============================] - 2s 285us/sample - loss: 0.4844 - accuracy: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 181us/sample - loss: 0.4302 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 180us/sample - loss: 0.4273 - accuracy: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 163us/sample - loss: 0.4215 - accuracy: 0.8165
Epoch 5/100
8000/8000 [==============================] - 1s 166us/sample - loss: 0.4150 - accuracy: 0.8282
Epoch 6/100
8000/8000 [==============================] - 1s 177us/sample - loss: 0.4104 - accuracy: 0.8316
Epoch 7/100
8000/8000 [==============================] - 1s 177us/sample - loss: 0.4069 - accuracy: 0.8335
Epoch 8/100
8000/8000 [==============================] - 1s 178us/sample - loss: 0.4049 - accuracy: 0.8359
Epoch 9/100
8000/8000 [==============================] - 1s 175us/sample - loss: 0.4031 - accuracy: 0.8344
Epoch 10/100
80

8000/8000 [==============================] - 2s 278us/sample - loss: 0.3441 - accuracy: 0.8624
Epoch 77/100
8000/8000 [==============================] - 2s 282us/sample - loss: 0.3439 - accuracy: 0.8616
Epoch 78/100
8000/8000 [==============================] - 3s 331us/sample - loss: 0.3442 - accuracy: 0.8621
Epoch 79/100
8000/8000 [==============================] - 3s 337us/sample - loss: 0.3447 - accuracy: 0.8618
Epoch 80/100
8000/8000 [==============================] - 2s 188us/sample - loss: 0.3442 - accuracy: 0.8616
Epoch 81/100
8000/8000 [==============================] - 3s 342us/sample - loss: 0.3436 - accuracy: 0.8634
Epoch 82/100
8000/8000 [==============================] - 2s 244us/sample - loss: 0.3442 - accuracy: 0.8621
Epoch 83/100
8000/8000 [==============================] - 2s 309us/sample - loss: 0.3440 - accuracy: 0.8621
Epoch 84/100
8000/8000 [==============================] - 3s 344us/sample - loss: 0.3434 - accuracy: 0.8616
Epoch 85/100
8000/8000 [=================

In [85]:
# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred[0:6]

array([[False],
       [False],
       [False],
       [False],
       [False],
       [ True]])

In [83]:

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1504,   91],
       [ 191,  214]], dtype=int64)